### ISSUE TITLE
utp selectiveAck extension crashes sometimes

### ISSUE THREAD

**Issue by moham96** [moham96/dtorrent_task#24]
sometimes the utp peer crash with this exception

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (length): Invalid value: Not in inclusive range 0..576460752303423487: -40608
#0      new _List.filled (dart:core-patch/array.dart)
#1      UTPSocketImpl.newSelectiveACK (package:utp_protocol/src/utp_socket_impl.dart:851:19)
#2      UTPSocketImpl.sendPacket (package:utp_protocol/src/utp_socket_impl.dart:1006:26)
#3      UTPSocketImpl.requestSendAck.<anonymous closure> (package:utp_protocol/src/utp_socket_impl.dart:881:12)
#4      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

this looks like a race condition or incorrect calculation of seq numbers, in any case i don't have reproducible steps for this crash, it happens rarely on my machine that makes it hard to debug and trace

**Comment by mountain-ysh** [comment]
I think have similar issue. I got in file utp_socket_impl.dart line 851 (var payload = List<int>.filled(c * 32, 0);) and this issue seems to be random when download "large(let's say 4GB)" file 
Exception has occurred.
RangeError (RangeError (length): Invalid value: Not in inclusive range 0..576460752303423487: -38624)
here's related code.

  SelectiveACK? newSelectiveACK() {
    if (_receivePacketBuffer.isEmpty) return null;
    _receivePacketBuffer.sort((a, b) {
      if (a > b) return 1;
      if (a < b) return -1;
      return 0;
    });
    var len = _receivePacketBuffer.last.seq_nr - lastRemoteSeq;
    var c = len ~/ 32;
    var r = len.remainder(32);
    if (r != 0) c++;
    var payload = List<int>.filled(c * 32, 0);
    var selectiveAck = SelectiveACK(lastRemoteSeq, payload.length, payload);
    for (var packet in _receivePacketBuffer) {
      selectiveAck.setAcked(packet.seq_nr);
    }
    return selectiveAck;
  }
